# SPDX-License-Identifier: GPL-3.0-or-later
# Weekly, grouped into one PR per ecosystem to save CI minutes. PRs go to develop.
version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      cargo:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
