// SPDX-License-Identifier: GPL-3.0-or-later
//! `openapi`: writes the API contract (ADR 0004) — `openapi.json` from `puddle-api`'s routes and
//! `schema.d.ts` generated from it by `openapi-typescript` — or, with `--check`, fails when
//! either committed file is stale.
//!
//! The TypeScript step needs Node (`node` and `npm` on `PATH`); the generator's version is pinned
//! in `crates/puddle-api/openapi/package-lock.json`. Without Node, `--check` still checks the
//! JSON and says it skipped the types, unless `CI` is set: there a missing Node fails.

use std::path::{Path, PathBuf};
use std::process::Command;

use crate::error::{Result, XtaskError};
use crate::tools::run;

/// The folder holding the contract and the generator's pin, relative to the workspace root.
pub const CONTRACT_DIR: &str = "crates/puddle-api/openapi";
/// The spec's file name.
pub const SPEC_FILE: &str = "openapi.json";
/// The generated types' file name.
pub const TYPES_FILE: &str = "schema.d.ts";

/// Prepended to the generator's output (the SPDX gate covers `.ts` files).
pub const TYPES_HEADER: &str = "// SPDX-License-Identifier: GPL-3.0-or-later\n\
// Generated by `cargo xtask openapi` from openapi.json (openapi-typescript); do not edit.\n";

/// What to do about the TypeScript types.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Types {
    /// Generate them; fail if Node is missing.
    Required,
    /// Generate them if Node is there, otherwise skip with a note.
    IfNodePresent,
}

/// The outcome of one run, for the message.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Report {
    /// What happened to the spec.
    pub spec: &'static str,
    /// What happened to the types.
    pub types: &'static str,
}

impl Report {
    /// One line for the terminal.
    #[must_use]
    pub fn line(&self) -> String {
        format!("openapi.json {}; schema.d.ts {}", self.spec, self.types)
    }
}

/// Runs `npm`/`node` for the TypeScript step. A trait so tests can stand in for Node.
pub trait TypeGenerator {
    /// Whether the generator can run here.
    fn available(&self) -> bool;
    /// TypeScript for `spec` (the generator's raw output, without [`TYPES_HEADER`]).
    ///
    /// # Errors
    ///
    /// When the generator fails.
    fn generate(&self, spec: &str) -> Result<String>;
}

/// The real generator: `npm ci` in the contract folder, then `openapi-typescript`.
#[derive(Debug, Clone)]
pub struct NodeGenerator {
    /// The contract folder (with `package.json` and the lock).
    pub dir: PathBuf,
    /// Scratch folder for the spec copy and the output.
    pub work: PathBuf,
}

fn npm() -> &'static str {
    if cfg!(windows) { "npm.cmd" } else { "npm" }
}

impl TypeGenerator for NodeGenerator {
    fn available(&self) -> bool {
        [Command::new("node"), Command::new(npm())]
            .iter_mut()
            .all(|c| run(c.arg("--version")).is_ok())
    }

    fn generate(&self, spec: &str) -> Result<String> {
        run(Command::new(npm())
            .arg("ci")
            .args(["--no-audit", "--no-fund", "--ignore-scripts", "--prefix"])
            .arg(&self.dir))?;
        std::fs::create_dir_all(&self.work)
            .map_err(|e| XtaskError::io(format!("create {}", self.work.display()), e))?;
        let input = self.work.join(SPEC_FILE);
        let output = self.work.join(TYPES_FILE);
        write(&input, spec)?;
        let cli = self.dir.join("node_modules/openapi-typescript/bin/cli.js");
        run(Command::new("node")
            .arg(cli)
            .arg(&input)
            .arg("-o")
            .arg(&output))?;
        read(&output)
    }
}

fn read(path: &Path) -> Result<String> {
    std::fs::read_to_string(path).map_err(|e| XtaskError::io(format!("read {}", path.display()), e))
}

fn write(path: &Path, text: &str) -> Result<()> {
    std::fs::write(path, text).map_err(|e| XtaskError::io(format!("write {}", path.display()), e))
}

/// The committed types file's content for `generated` output.
#[must_use]
pub fn with_header(generated: &str) -> String {
    format!("{TYPES_HEADER}{generated}")
}

/// Writes (or with `check`, compares) the spec `spec` and its types in `dir`.
///
/// # Errors
///
/// [`XtaskError::Stale`] naming the stale file when checking, [`XtaskError::Tool`] when Node is
/// required but missing or the generator fails, or a file error.
pub fn openapi(
    dir: &Path,
    spec: &str,
    check: bool,
    types: Types,
    generator: &dyn TypeGenerator,
) -> Result<Report> {
    let spec_path = dir.join(SPEC_FILE);
    let types_path = dir.join(TYPES_FILE);
    let spec_state = if check {
        if read(&spec_path).ok().as_deref() != Some(spec) {
            return Err(XtaskError::Stale(spec_path));
        }
        "is current"
    } else {
        write(&spec_path, spec)?;
        "written"
    };
    if !generator.available() {
        return match types {
            Types::Required => Err(XtaskError::Tool {
                command: "node --version".into(),
                detail: "Node is needed to generate schema.d.ts (install Node 22 or newer)".into(),
            }),
            Types::IfNodePresent => Ok(Report {
                spec: spec_state,
                types: "not checked: Node is not installed (CI checks it)",
            }),
        };
    }
    let generated = with_header(&generator.generate(spec)?);
    let types_state = if check {
        if read(&types_path).ok() != Some(generated) {
            return Err(XtaskError::Stale(types_path));
        }
        "is current"
    } else {
        write(&types_path, &generated)?;
        "written"
    };
    Ok(Report {
        spec: spec_state,
        types: types_state,
    })
}

#[cfg(test)]
mod tests {
    use std::cell::Cell;

    use super::*;

    struct Fake {
        node: bool,
        calls: Cell<u32>,
    }

    impl TypeGenerator for Fake {
        fn available(&self) -> bool {
            self.node
        }

        fn generate(&self, spec: &str) -> Result<String> {
            self.calls.set(self.calls.get() + 1);
            Ok(format!("export type Spec = {};\n", spec.len()))
        }
    }

    fn fake(node: bool) -> Fake {
        Fake {
            node,
            calls: Cell::new(0),
        }
    }

    #[test]
    fn write_then_check_passes_and_drift_fails() {
        let dir = tempfile::tempdir().unwrap();
        let g = fake(true);
        let r = openapi(dir.path(), "{}\n", false, Types::Required, &g).unwrap();
        assert_eq!(r.line(), "openapi.json written; schema.d.ts written");
        let types = std::fs::read_to_string(dir.path().join(TYPES_FILE)).unwrap();
        assert!(types.starts_with("// SPDX-License-Identifier: GPL-3.0-or-later\n"));
        let r = openapi(dir.path(), "{}\n", true, Types::Required, &g).unwrap();
        assert_eq!(r.line(), "openapi.json is current; schema.d.ts is current");
        assert_eq!(g.calls.get(), 2);

        let err = openapi(dir.path(), "{ }\n", true, Types::Required, &g).unwrap_err();
        assert!(
            matches!(err, XtaskError::Stale(ref p) if p.ends_with(SPEC_FILE)),
            "{err}"
        );
        assert!(err.to_string().contains("cargo xtask openapi"), "{err}");

        std::fs::write(dir.path().join(TYPES_FILE), "edited by hand").unwrap();
        let err = openapi(dir.path(), "{}\n", true, Types::Required, &g).unwrap_err();
        assert!(
            matches!(err, XtaskError::Stale(ref p) if p.ends_with(TYPES_FILE)),
            "{err}"
        );
    }

    #[test]
    fn missing_node_skips_locally_and_fails_when_required() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(SPEC_FILE), "{}\n").unwrap();
        let r = openapi(dir.path(), "{}\n", true, Types::IfNodePresent, &fake(false)).unwrap();
        assert!(r.types.starts_with("not checked"), "{}", r.line());
        let err = openapi(dir.path(), "{}\n", true, Types::Required, &fake(false)).unwrap_err();
        assert!(err.to_string().contains("Node is needed"), "{err}");
        // A stale spec is reported even without Node.
        let err = openapi(dir.path(), "[]\n", true, Types::IfNodePresent, &fake(false));
        assert!(matches!(err, Err(XtaskError::Stale(_))));
    }

    #[test]
    fn generator_failures_surface() {
        let g = NodeGenerator {
            dir: PathBuf::from("/nonexistent/puddle-openapi"),
            work: std::env::temp_dir().join("xtask-openapi-test"),
        };
        if g.available() {
            assert!(g.generate("{}").is_err());
        }
    }
}
